//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2019 by PDFTron Systems Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CGeometryCollection
#define PDFTRON_H_CGeometryCollection

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_GeometryCollection_tag;
typedef struct TRN_GeometryCollection_tag* TRN_GeometryCollection;


/* methods: */
TRN_API TRN_GeometryCollectionSnapToNearest(TRN_GeometryCollection self, double x, double y, TRN_Point* result);
TRN_API TRN_GeometryCollectionSnapToNearestPixel(TRN_GeometryCollection self, double x, double y, double dpi, TRN_Point* result);

TRN_API TRN_GeometryCollectionDestroy(TRN_GeometryCollection self);


#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CGeometryCollection */
